### ISSUE TITLE
Add WHEN Flowcards for Link Status Events

### ISSUE THREAD

**Issue by jamisonbennett** [jamisonbennett/homey-tp-link-managed-switch#2]
This request is from #1 

> Are there IF flowcards possible too? Like when a link goes down or things like that? Or is this not possible since you can only use it's webinterface?

I'm considering implementing this, potentially over the weekend. However, since this would rely on polling, there's a chance it may not capture every transition.

Before proceeding, I have a few questions:

1. Would this feature still be useful if it could occasionally "miss" an event?
2. Do you need immediate responses to these events, or is a delay of up to a minute acceptable?
3. Do you have a suggestion for how long of an interval would be acceptable? (if its under a few seconds, this would not be a possibility)

I should be able to create a WHEN trigger for these events, but please note it might miss quick transitions (e.g., if a cable is unplugged and reconnected before the next polling interval).

**Comment by HenkRenting** [comment]
I already thought you might need polling. I suppose such a WHEN card isn't very useful then.
Perhaps other WHEN cards are though. Haven't thought of any other yet.

**Comment by jamisonbennett** [comment]
I have added this feature to the version [0.1.2](https://github.com/jamisonbennett/homey-tp-link-managed-switch/tree/v0.1.2). The code change has been made and it has been submitted to the App Store for review.

The polling interval is once per minute.

**Comment by jamisonbennett** [comment]
Version [0.1.2](https://github.com/jamisonbennett/homey-tp-link-managed-switch/tree/v0.1.2) is live now.
